services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service-app
    hostname: payment-service
    ports:
      - "8082:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      APP_KAFKA_AVRO_BOOTSTRAP_SERVERS: kafka:9094
      APP_KAFKA_AVRO_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: -Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=100
    networks:
      - bootcamp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

networks:
  bootcamp-network:
    external: true
